/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-10-17 14:13:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import cafein.ConnectDB;

public final class csManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/include/footer.jsp", Long.valueOf(1570291316694L));
    _jspx_dependants.put("/view/include/header.jsp", Long.valueOf(1571319574211L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("  <title>Cafe-in Admin</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/dist/css/adminlte.min.css\">\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- iconic icon -->\r\n");
      out.write("  <link href=\"../../assets/open-iconic-master/font/css/open-iconic-bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- DataTables -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css\">\r\n");
      out.write("  <!-- custom css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/custom/custom.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- checkBox css -->\r\n");
      out.write("  <link href=\"../../assets/square/blue.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"../../assets/icheck.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <div class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <h1 class=\"m-0 text-dark\">cs ê´ë¦¬</h1>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\">Starter Page</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content-header -->\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("        \t<div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("              <h3 class=\"card-title\">íì´ë¸</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.card-header -->\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <table id=\"menuTBL\" class=\"table table-bordered table-striped\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>ë²í¸</th>\r\n");
      out.write("                  <th>ì¬ì©ì ID</th>\r\n");
      out.write("                  <th>ì ëª©</th>\r\n");
      out.write("                  <th>ì í</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                \r\n");
      out.write("                ");

	                int csNum;
	                String userID, csTitle, csType;
                	ConnectDB connectDB = ConnectDB.getInstance();
	            	Connection con = connectDB.openConnection();
	            	Statement stmt = con.createStatement();
	            	String sql = "select * from complain";
	        		ResultSet rs = stmt.executeQuery(sql);
	            	
	        		while(rs.next()) {
	        			csNum = rs.getInt(1);
	        			userID = rs.getString(2);
	        			csTitle = rs.getString(3);
	        			csType = rs.getString(4);
	        	
      out.write("\t\r\n");
      out.write("\t        \t\t<tr>\r\n");
      out.write("\t        \t\t\t<td>");
      out.print( csNum );
      out.write("</td>\r\n");
      out.write("\t        \t\t\t<td>");
      out.print( userID );
      out.write("</td>\r\n");
      out.write("\t        \t\t\t<td>");
      out.print( csTitle );
      out.write("</td>\r\n");
      out.write("\t        \t\t\t<td>");
      out.print( csType );
      out.write("</td>\r\n");
      out.write("        \t\t\t</tr>\r\n");
      out.write("\t        \t");
 
	        		}
	        		rs.close();
	        		stmt.close();
	        		connectDB.closeConnection(con);
	        	
      out.write("\t\t\r\n");
      out.write("                </tbody>\r\n");
      out.write("                <tfoot>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>ë²í¸</th>\r\n");
      out.write("                  <th>ì¬ì©ì ID</th>\r\n");
      out.write("                  <th>ì ëª©</th>\r\n");
      out.write("                  <th>ì í</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.card-body -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.card -->\r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-12 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("    <div class=\"p-3\">\r\n");
      out.write("      <h5>Title</h5>\r\n");
      out.write("      <p>Sidebar content</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("  \r\n");
      out.write("  <!-- Main Footer -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <!-- To the right -->\r\n");
      out.write("    <div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("      Anything you want\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Default to the left -->\r\n");
      out.write("    <strong>Copyright &copy; 2014-2019 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong> All rights reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- REQUIRED SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"../../assets/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"../../assets/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- DataTables -->\r\n");
      out.write("<script src=\"../../assets/plugins/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"../../assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"../../assets/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE for demo purposes -->\r\n");
      out.write("<script src=\"../../assets/dist/js/demo.js\"></script>\r\n");
      out.write("<!-- page script -->\r\n");
      out.write("<script>\r\n");
      out.write("  $(function () {\r\n");
      out.write("    $(\"#menuTBL\").DataTable();\r\n");
      out.write("    $('#example2').DataTable({\r\n");
      out.write("      \"paging\": true,\r\n");
      out.write("      \"lengthChange\": false,\r\n");
      out.write("      \"searching\": false,\r\n");
      out.write("      \"ordering\": true,\r\n");
      out.write("      \"info\": true,\r\n");
      out.write("      \"autoWidth\": false,\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
