/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2019-10-17 14:13:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import cafein.ConnectDB;

public final class guide_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/view/include/footer.jsp", Long.valueOf(1570291316694L));
    _jspx_dependants.put("/view/include/main_aside.jsp", Long.valueOf(1571321019703L));
    _jspx_dependants.put("/view/include/nav_header.jsp", Long.valueOf(1571318664649L));
    _jspx_dependants.put("/view/include/header.jsp", Long.valueOf(1571319574211L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("This is a starter template page. Use this page to start your new project from\r\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("\r\n");
      out.write("  <title>Cafe-in Admin</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome Icons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/dist/css/adminlte.min.css\">\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- iconic icon -->\r\n");
      out.write("  <link href=\"../../assets/open-iconic-master/font/css/open-iconic-bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- DataTables -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css\">\r\n");
      out.write("  <!-- custom css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/custom/custom.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- checkBox css -->\r\n");
      out.write("  <link href=\"../../assets/square/blue.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"../../assets/icheck.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  </head>");
      out.write("<body class=\"hold-transition sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("  <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\r\n");
      out.write("    <!-- Left navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"index3.html\" class=\"nav-link\">홈</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item d-none d-sm-inline-block\">\r\n");
      out.write("        <a href=\"#\" class=\"nav-link\">Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- SEARCH FORM -->\r\n");
      out.write("    <form class=\"form-inline ml-3\">\r\n");
      out.write("      <div class=\"input-group input-group-sm\">\r\n");
      out.write("        <input class=\"form-control form-control-navbar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <div class=\"input-group-append\">\r\n");
      out.write("          <button class=\"btn btn-navbar\" type=\"submit\">\r\n");
      out.write("            <i class=\"fas fa-search\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Right navbar links -->\r\n");
      out.write("    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("      <!-- Messages Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-comments\"></i>\r\n");
      out.write("          <span class=\"badge badge-danger navbar-badge\">3</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"../../assets/dist/img/user1-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 mr-3 img-circle\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Brad Diesel\r\n");
      out.write("                  <span class=\"float-right text-sm text-danger\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">Call me whenever you can...</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"../../assets/dist/img/user8-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  John Pierce\r\n");
      out.write("                  <span class=\"float-right text-sm text-muted\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">I got your message bro</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <!-- Message Start -->\r\n");
      out.write("            <div class=\"media\">\r\n");
      out.write("              <img src=\"../../assets/dist/img/user3-128x128.jpg\" alt=\"User Avatar\" class=\"img-size-50 img-circle mr-3\">\r\n");
      out.write("              <div class=\"media-body\">\r\n");
      out.write("                <h3 class=\"dropdown-item-title\">\r\n");
      out.write("                  Nora Silvester\r\n");
      out.write("                  <span class=\"float-right text-sm text-warning\"><i class=\"fas fa-star\"></i></span>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p class=\"text-sm\">The subject goes here</p>\r\n");
      out.write("                <p class=\"text-sm text-muted\"><i class=\"far fa-clock mr-1\"></i> 4 Hours Ago</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Message End -->\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Messages</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <!-- Notifications Dropdown Menu -->\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("          <i class=\"far fa-bell\"></i>\r\n");
      out.write("          <span class=\"badge badge-warning navbar-badge\">15</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu dropdown-menu-lg dropdown-menu-right\">\r\n");
      out.write("          <span class=\"dropdown-header\">15 Notifications</span>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-envelope mr-2\"></i> 4 new messages\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">3 mins</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-users mr-2\"></i> 8 friend requests\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">12 hours</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("            <i class=\"fas fa-file mr-2\"></i> 3 new reports\r\n");
      out.write("            <span class=\"float-right text-muted text-sm\">2 days</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"dropdown-item dropdown-footer\">See All Notifications</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" data-widget=\"control-sidebar\" data-slide=\"true\" href=\"#\"><i\r\n");
      out.write("            class=\"fas fa-th-large\"></i></a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- /.navbar -->");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("\t");
      out.write("<!-- Main Sidebar Container -->\r\n");
      out.write("<!--   <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">  -->\r\n");
      out.write("    <!-- Brand Logo -->\r\n");
      out.write("    <a href=\"index3.html\" class=\"brand-link\">\r\n");
      out.write("      <img src=\"../../assets/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\"\r\n");
      out.write("           style=\"opacity: .8\">\r\n");
      out.write("      <span class=\"brand-text font-weight-light\"><b>Cafe-in</b> admin</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("      <!-- Sidebar user panel (optional) -->\r\n");
      out.write("      <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
      out.write("        <div class=\"image\">\r\n");
      out.write("          <!-- <img src=\"../../assets/dist/img/user2-160x160.jpg\" class=\"img-circle elevation-2\" alt=\"User Image\"> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("          <a href=\"#\" class=\"d-block\"><!--Alexander Pierce--></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Menu -->\r\n");
      out.write("      <nav class=\"mt-2\">\r\n");
      out.write("        <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("          <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("               with font-awesome or any other icon font library -->\r\n");
      out.write("   \r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link\">\r\n");
      out.write("              <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <p>\r\n");
      out.write("                 홈   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"userManage.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 회원관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 주문관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"employeeManage.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 직원관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 매출관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 재고관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"menuManage.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 메뉴관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("                  \r\n");
      out.write("           <li class=\"nav-item\">\r\n");
      out.write("            <a href=\"csManage.jsp\" class=\"nav-link\">\r\n");
      out.write("              <!-- <span class=\"nav-icon oi oi-home\" aria-hidden=\"true\"></span> -->\r\n");
      out.write("              <p>\r\n");
      out.write("                 CS관리   \r\n");
      out.write("                <span class=\"badge badge-info right\"><!-- 숫자 --></span>\r\n");
      out.write("              </p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- /.sidebar-menu -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.sidebar -->\r\n");
      out.write("  <!--   </aside>  -->");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <div class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <h1 class=\"m-0 text-dark\">Starter Page</h1>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\">Starter Page</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content-header -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\t\t<!-- content 시작 -->\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("\t\t<!-- content 끝 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("  <aside class=\"control-sidebar control-sidebar-dark\">\r\n");
      out.write("    <!-- Control sidebar content goes here -->\r\n");
      out.write("    <div class=\"p-3\">\r\n");
      out.write("      <h5>Title</h5>\r\n");
      out.write("      <p>Sidebar content</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!-- Main Footer -->\r\n");
      out.write("  <footer class=\"main-footer\">\r\n");
      out.write("    <!-- To the right -->\r\n");
      out.write("    <div class=\"float-right d-none d-sm-inline\">\r\n");
      out.write("      Anything you want\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Default to the left -->\r\n");
      out.write("    <strong>Copyright &copy; 2014-2019 <a href=\"https://adminlte.io\">AdminLTE.io</a>.</strong> All rights reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- REQUIRED SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"../../assets/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"../../assets/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- DataTables -->\r\n");
      out.write("<script src=\"../../assets/plugins/datatables/jquery.dataTables.js\"></script>\r\n");
      out.write("<script src=\"../../assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"../../assets/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE for demo purposes -->\r\n");
      out.write("<script src=\"../../assets/dist/js/demo.js\"></script>\r\n");
      out.write("<!-- page script -->\r\n");
      out.write("<script>\r\n");
      out.write("  $(function () {\r\n");
      out.write("    $(\"#menuTBL\").DataTable();\r\n");
      out.write("    $('#example2').DataTable({\r\n");
      out.write("      \"paging\": true,\r\n");
      out.write("      \"lengthChange\": false,\r\n");
      out.write("      \"searching\": false,\r\n");
      out.write("      \"ordering\": true,\r\n");
      out.write("      \"info\": true,\r\n");
      out.write("      \"autoWidth\": false,\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
